#!/usr/bin/env python3
"""
Interface Test Script Generator

This script generates executable interface test scripts based on JSON test cases
generated by the test case generation script.
It replaces the original generate_interface_tests.py with a cleaner interface.
"""

import sys
import os

# Add the src directory to the Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from src.utils.config import Config
from src.core.interface_test_generator import InterfaceTestGenerator


def main():
    """Main function to generate interface test scripts"""
    print("=== TSP Interface Test Generation Script ===")

    # Initialize configuration
    config = Config()

    # Initialize interface test generator
    generator = InterfaceTestGenerator(config)

    # Run the generation process
    success = generator.run()

    if success:
        print("\n✅ Interface test generation completed successfully!")
        sys.exit(0)
    else:
        print("\n❌ Interface test generation failed!")
        sys.exit(1)


if __name__ == "__main__":
    main()